### ISSUE TITLE
add support for custom http status code messages

### ISSUE THREAD

**Issue by ryanguill** [lucee/lucee-dockerfiles#16]
If I could get you to add this to the bottom of the `catalina.properties` file it would save me a step:

`org.apache.coyote.USE_CUSTOM_STATUS_MSG_IN_HEADER=true`

relevant docs if necessary: https://tomcat.apache.org/tomcat-8.0-doc/config/systemprops.html

I need this for taffy: http://docs.taffy.io/3.0.0#custom-http-status-messages

**Comment by ryanguill** [comment]
If you're in agreement I can also send a PR if thats easier.

**Comment by modius** [comment]
PR Sounds good.

Is there any reason this isn't a good idea to set true?

**Comment by ryanguill** [comment]
Not that I am aware of, but ill do a bit of research to be sure before I
send the PR.

On Sunday, February 7, 2016, Geoff Bowers <notifications@github.com> wrote:

> PR Sounds good.
>
> Is there any reason this isn't a good idea to set true?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/lucee/lucee-dockerfiles/issues/16#issuecomment-181122029>
> .
>


-- 
Ryan Guill
ryanguill@gmail.com
(901) 257-9264

**Comment by ryanguill** [comment]
I can't find any reason not to enable it and I can't find any way to make it driven by an environment variable - although admittedly I am a bit out of my element when it comes to fine tuning tomcat.  More research necessary or would you be ok with a PR that would enable it directly?

**Comment by modius** [comment]
Lets enable it by default as that seems genuinely useful. Folks can always override the catalina file in their own project for specific changes.

**Comment by ryanguill** [comment]
https://github.com/lucee/lucee-dockerfiles/pull/18
