### ISSUE TITLE
None of the latest builds are working

### ISSUE THREAD

**Issue by gregmoser** [lucee/lucee-dockerfiles#17]
Please see my comments here:
https://groups.google.com/d/msg/lucee/oN33IPe414U/x1IlmVMZEgAJ

Based on my testing the following is true.

**This Works**
lucee/lucee-tomcat:4.5.1 

**However These do NOT**
lucee/lucee-tomcat:latest
lucee/lucee-tomcat:4.5.2 (same as latest I believe, but maybe not)
lucee/lucee4:latest
lucee/lucee4:4.5.2.018 (same as latest I believe, but maybe not)
lucee/lucee4:4.5.1.024
lucee/lucee5:latest

**Comment by modius** [comment]
When you say doesn't work, what are you seeing?

If you are not using the nginx compound images you will need to expose port 8888 to get access to the default tomcat web server.

**Comment by gregmoser** [comment]
I think that I understand what the issue is.

lucee/lucee-tomcat:4.5.1 used to expose port 8080, and all of the latest versions of all the containers don't expose any ports at all by default.  Is that correct?

**Comment by modius** [comment]
For better or worse, we have standardised the port usage based on all the other Lucee installers; namely port 8888.

The base image doesn't expose any ports except those exposed by the underlying tomcat base image; that is port 8080.  We could expose the 8888 port by default but many projects that would extend the Lucee base image (for example, `lucee/lucee4-nginx`) do not need that port exposed.

`lucee/lucee4-nginx` does expose 80/443 for HTTP/HTTPS traffic.  This image would give you a demonstrable build but blocks the admin by default for security reasons ;)

I added a bit more discussion on port 8888 here: https://github.com/lucee/lucee-dockerfiles/issues/13

**Comment by gregmoser** [comment]
Thanks for the info, totally makes sense and I will update my slatwall containers with this understanding.

As an aside, I would like to continue the discussion around the base lucee containers specifically around configuration best practices.  For example I've build a script that can set the lucee admin password from an environment variable, but not sure if you have other planned configuration points.

Where would you like to talk more about these things?

**Comment by modius** [comment]
Hacking on aspects of lucee server best over here: http://lang.lucee.org/c/hacking
