### ISSUE TITLE
CGI remote address points to the proxy

### ISSUE THREAD

**Issue by mrerichoffman** [lucee/lucee-dockerfiles#26]
The default configuration for nginx-lucee4 does not expose the correct cgi remote address (cgi.remote_addr), it points to proxy ip 127.0.0.1 - instead of the real ip. Found an article that has a fix for Railo by putting in a configuration tweak for tomcat - https://kisdigital.wordpress.com/2011/08/19/retain-remote-address-when-proxying-railo-with-nginx/

<Valve className="org.apache.catalina.valves.RemoteIpValve"  />

I can confirm the fix works as expected on Lucee, can someone update the tomcat config for the docker image in 4.5 and 5.0 and test out the change?

**Comment by modius** [comment]
> Tomcat version 6.0.24 added a way to translate the X-Real-IP header and allow Railo to use that without having to do any header-fu.  All you have to do is add one line to your server.xml under the <Engine> container:

```
<Valve className="org.apache.catalina.valves.RemoteIpValve"  />
```

**Comment by modius** [comment]
This looks like an enhancement we're trialling internally; the only difference being we're adding a couple of extra attributes to the valve:

https://github.com/lucee/lucee-dockerfiles/issues/27

Extremely likely this will go through into the base images shortly.
