### ISSUE TITLE
Remove default lucee configs from build

### ISSUE THREAD

**Issue by modius** [lucee/lucee-dockerfiles#30]
Currently we copy lucee config templates into the build.  However, we run the risk of getting out of date with the default templates generated by the lucee build process. Should delete all lucee config defaults, and allow lucee start-up to deploy system default configs as standard.

We should be focused on providing the simplest, most reliable image for folks to build on in their own projects.

Note, this may make it harder for devs new to Docker to work out how to implement their own configs.. probably needs to be part of a more detailed documentation effort for "Getting Started with Lucee on Docker" type of thing.

**Comment by justincarter** [comment]
I'm going to close this issue as it's probably a good idea to offer up a default config per Lucee minor version, and also keep them up to date with recommended settings (something I'm yet to tackel but is a slightly different issue). This also makes it easy to understand the out of the box configuration at a glance.
