### ISSUE TITLE
CFCHART call back url for image blocked by admin redirect on NGINX

### ISSUE THREAD

**Issue by modius** [lucee/lucee-dockerfiles#36]
getting the following blocked on the container:
>`/lucee/graph.cfm?img=53d55bb8f3dabc853335b357dae8cb91&type=png`

assuming this is some random thing for CFCHART or equiv.. guessing we need to allow this through?

**Comment by justincarter** [comment]
An optional section of configuration has been added to nginx to support cfchart requests via `/lucee/graph.cfm` but for now it is disabled by default (just to avoid fingerprinting via that URL), and can be enabled by end users by customising their nginx config as per the example.

https://github.com/lucee/lucee-dockerfiles/commit/d344cc7599cc09a6d510f3fca80a68dc72a0cb53#diff-6e3b94cc2962c9b71ad79693ede922cb
