### ISSUE TITLE
/lucee/admin return a 404

### ISSUE THREAD

**Issue by johnjarrard** [lucee/lucee-dockerfiles#37]
I've setup the Lucee_nginx51 docker exactly as described here but cannot get the admin site to load.  The sample "Hello Cruel World!" index.cfm page load fine.  I've altered the default.conf file as follow:

`location ~* /lucee/ {
    # allow 10.0.0.1;
    allow all;
    # deny all;
  }`

Before I did that, I was getting a 403.

**Comment by modius** [comment]
The following block in the NGINX compound image is deliberately blocking access to the Admin for security reasons:

```
  location ~* /lucee/ {
    # allow 10.0.0.1; # Add your IP address here
    deny all; # block access
  }
```

If you need access to the Admin you will need to remove that entry.  Do this by creating your own Dockerfile that extends the official lucee base image, and COPY in your own default.conf

For example:

```
FROM lucee/lucee4-nginx:4.5.5.006

# NGINX configs
COPY config/nginx/ /etc/nginx/

# Deploy codebase to container
COPY myprojectcode /var/www/
```

**Comment by isapir** [comment]
> If you need access to the Admin you will need to remove that entry.

Or preferably, add your own IP or subnet with an allow directive.
