### ISSUE TITLE
Internal Lucee Directories that Should Be Persistent

### ISSUE THREAD

**Issue by jamiejackson** [lucee/lucee-dockerfiles#41]
I just thought of this yesterday: There is at least one directory which probably ought to be thought of as persistent: the mail spool. If the container is recreated while there is a flaky mail connection, Lucee ought to pick up where it left off when the container restarts. This should be called out in VOLUME and documented. There may be other directories like this that I haven’t thought of, but after having lost mail for a span, this one made itself obvious.

For some unknown reason the mail queue is [supposedly to be found](https://dev.lucee.org/t/where-are-the-undelivered-emails/1782/3) in less than obvious `/opt/lucee/web/remote-client/open` directory.

**Comment by jamiejackson** [comment]
FYI, my custom image now has the following, to help document some useful volume possibilities that a consumer might not have thought of:

```Dockerfile
VOLUME [ \
 "/opt/fusionreactor/log", \
 "/opt/lucee/web/logs", \
 "/opt/lucee/web/remote-client", \
 "/usr/local/tomcat/logs", \
 "/var/www" \
]
```

**Comment by modius** [comment]
Thanks for that!

The problem with logs.. the more members in the cluster you have the more persistent log locations you have.  You can look to cluster the volumes, or map volumes to a shared resource etc.  but this can make your infrastructure less generic.

A popular approach is to send logging to a "log drain" -- a specific service that aggregates your nominated logs.

Given the intimate nature of many infrastructure set ups we tend towards keeping the image as generic as possible.  VOLUME is something that is difficult to unset once the base image puts it in place.
