### ISSUE TITLE
Keep Images Up to Date

### ISSUE THREAD

**Issue by jamiejackson** [lucee/lucee-dockerfiles#42]
Consider that the [`lucee/lucee4`](https://hub.docker.com/r/lucee/lucee4/) image hasn't seen an update in over a year, but IIRC, there have been several Tomcat CVEs in the meantime.

The community assumes that supported tags are kept up-to-date.

This is somewhat related to #40.

**Comment by justincarter** [comment]
Lucee 4 images were updated with a security patch in mid-August, so it's on the latest available Tomcat 8.0.53 and JRE8 as at that date. Lucee 4.5.x is also basically EOL, we are recommending that everyone migrate to Lucee 5.2.x as soon as possible (https://dev.lucee.org/t/end-of-life-for-lucee-4-5/4093).
