### ISSUE TITLE
Clarification on Tomcat Manager App

### ISSUE THREAD

**Issue by mattblaha** [lucee/lucee-dockerfiles#47]
Apologies if this is more of a question than an issue:

I notice that logs get created in the image for the manager app. Though I cannot find it anywhere, is it running and accessible?

To work with various custom apps, I'm running the straight tomcat image behind httpd. I'm blocking /lucee, WEB-INF, and META-INF in httpd . . . should I be concerned about exposing the manager app?

**Comment by justincarter** [comment]
Sorry, I thought I had replied to this by email... The Tomcat Manager is removed during the build so we must have missed the logs in the cleanup;

https://github.com/lucee/lucee-dockerfiles/blob/master/5.2/Dockerfile#L15
