### ISSUE TITLE
Update Hello World template

### ISSUE THREAD

**Issue by modius** [lucee/lucee-dockerfiles#5]
Make a pretty hello world template.  Currently dumps a few server internals for debugging, with the understanding that developers will use project specific Dockerfile to build FROM the base image.

**Comment by justincarter** [comment]
Hello world / sample home page has been copied from Lucee Express, with updated links;

https://github.com/lucee/lucee-dockerfiles/commit/ee7f52dc05050ba62daad7911755d79e6e67f0e0
https://github.com/lucee/lucee-dockerfiles/commit/057885b1c3a64431ee99f1214897afdde0a50e98
