### ISSUE TITLE
Document what "Light" Means in Image Tags

### ISSUE THREAD

**Issue by jamiejackson** [lucee/lucee-dockerfiles#50]
"Light" images are available, but it's not necessarily apparent what that means. Please consider  adding an explanation to the documentation.

**Comment by justincarter** [comment]
The Lucee "Light" JAR is a small version that contains no extensions, this is now documented here under the `-light` bullet point on how the tags work;
https://github.com/lucee/lucee-dockerfiles#how-the-tags-work
