### ISSUE TITLE
An illegal reflective access operation has occurred

### ISSUE THREAD

**Issue by fransvanberckel** [lucee/lucee-dockerfiles#56]
About 5.3.77-nginx: While starting tomcat and lucee as non root.

WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.apache.felix.framework.ext.ClassPathExtenderFactory$DefaultClassLoaderExtender (file:/usr/local/tomcat/lucee/lucee.jar) to method java.net.URLClassLoader.addURL(java.net.URL)
WARNING: Please consider reporting this to the maintainers of org.apache.felix.framework.ext.ClassPathExtenderFactory$DefaultClassLoaderExtender
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
ERROR: Error creating bundle cache.

That's resolved with the latest, felix.framework-6.0.3?
http://svn.apache.org/repos/asf/felix/releases/org.apache.felix.framework-6.0.3/doc/changelog.txt

**Comment by fransvanberckel** [comment]
It's reported by LDEV-2300 as well.

**Comment by fransvanberckel** [comment]
Check lucee.jar-5.3.5.3 has felix.version=6.0.2. Please update LDEV-2300 as well ;-)

**Comment by justincarter** [comment]
Can you try the lucee/lucee:5.3.5.3-SNAPSHOT tag? Each commit has a
snapshot build so that you can try the bleeding edge commits :)

**Comment by fransvanberckel** [comment]
I am not able to reproduce this but at local machine. But if i build and check /usr/local/tomcat/logs/catalina.out from lucee:5.3.5.3-SNAPSHOT, it's still there.

**Comment by justincarter** [comment]
The WARNING is still there in the latest build (5.3.4.77);

```
10-Feb-2020 23:45:57.054 INFO [main] org.apache.catalina.core.StandardEngine.startInternal Starting Servlet engine: [Apache Tomcat/9.0.30]
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.apache.felix.framework.ext.ClassPathExtenderFactory$DefaultClassLoaderExtender (file:/usr/local/tomcat/lucee/lucee.jar) to method java.net.URLClassLoader.addURL(java.net.URL)
WARNING: Please consider reporting this to the maintainers of org.apache.felix.framework.ext.ClassPathExtenderFactory$DefaultClassLoaderExtender
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```

However the error that you were getting (`ERROR: Error creating bundle cache.`) isn't present. There doesn't seem to be any negative side effects other than the warning at this time. Do you think there's anything else we should look at to try to resolve this?

**Comment by jamiejackson** [comment]
I'd prefer if we could get rid of the warnings; otherwise, one has to keep an inventory of "ignorable" errors/warnings when troubleshooting, updating Lucee, etc.

Otherwise, you have thoughts like:
* Did my latest release / lucee upgrade cause this error/warning, or was it there before?
* Does it matter? Let me go spend some cycles researching/remembering if I can ignore this or not.

**Comment by justincarter** [comment]
Agreed.

At this time I don't know of a way to remove the warning though, see;
https://luceeserver.atlassian.net/browse/LDEV-2300

I'm not sure if Lucee can suppress the Felix warning, but it seems like an upstream issue more than a Docker image issue?

**Comment by cybersonic** [comment]
This happens whether in docker or not. Since there is already a ticket for it in the main lucee repo, we can close this ticket.
