### ISSUE TITLE
Need a final for 5.3.6.61

### ISSUE THREAD

**Issue by murphydan** [lucee/lucee-dockerfiles#63]
It looks like there is a snapshot for 5.3.6.61 but not a final. Was that just mistagged and is actually the final?

https://hub.docker.com/r/lucee/lucee/tags?page=1&name=5.3.6

**Comment by modius** [comment]
Snapshots are automated;
https://hub.docker.com/r/lucee/lucee/tags?page=1&name=5.3.6

Releases are manual and are built whenever we see an announcement or get pinged by someone :)

Those releases should now be available -- apologies for the delay.
