### ISSUE TITLE
Need image rebuild to update Tomcat to latest 9.0.x due to Rewrite bug

### ISSUE THREAD

**Issue by SimonHooker** [lucee/lucee-dockerfiles#65]
https://bz.apache.org/bugzilla/show_bug.cgi?id=64432

Currently lucee/lucee:5.3.6.61 includes Tomcat 9.0.35, as does the bleeding edge.
This version of tomcat includes the bug mentioned above, which in turn prevents using more than 1 rewrite rule within a configuration which in turn kind of breaks our servers.

Please can the image get rebuilt to the latest 9.0-jdk11-openjdk which would be 9.0.37 (released 4 days ago), or at least 9.0.36 which includes a fix for the above.

**Comment by SimonHooker** [comment]
I've since rebuilt + pushed up to a private repo so this is less of a priority now from a personal perspective, however it would probably be good to update the official Lucee image to include the minor Tomcat fixes up to 9.0.37

**Comment by SimonHooker** [comment]
Hi there, please can the image be rebuilt?

**Comment by justincarter** [comment]
I've just done a rebuild for 5.3.6.61, please let me know if that fixes the Tomcat rewrite issue.

**Comment by SimonHooker** [comment]
Hi Justin,

Happy to confirm that this has resolved the issue I was experiencing, thank you.
