### ISSUE TITLE
CFDOCUMENT not working in base image

### ISSUE THREAD

**Issue by modius** [lucee/lucee-dockerfiles#7]
CFDOCUMENT not working as official Tomcat uses a headless openjdk that's missing the fonts and font-manager.

This can be fixed relatively easily by adding the following to the top of the Dockerfile:

```
# upgrade openjdk to include font tools for cfdocument
RUN apt-get update && apt-get install -y openjdk-8-jre && rm -rf /var/lib/apt/lists/*
```

Not sure whether this should be part of the standard build, a variant, or just advice to developers.  Adding all the non-headless stuff inflates image size but is essential for folks relying on CFDOCUMENT and probably other features that need font rendering.

**Comment by modius** [comment]
Anecdotal report that this is now working in the standard Tomcat 8 base image.  This may be resolved now that all images are running on Tomcat 8.  Need to confirm.

**Comment by elpete** [comment]
FWIW, adding that code snippet did not fix the missing styles or missing images issues that we are seeing. cc @murphydan

**Comment by justincarter** [comment]
I can't pinpoint the exact time that cfdocument was fixed, but it's definitely working currently as has been for some time (2 years). All Lucee versions are on the same version of Tomcat and the JRE, so it should be working in all unless this was specific to Lucee 4.5.x, which is now EOL.
