### ISSUE TITLE
CVEs

### ISSUE THREAD

**Issue by VirtuallyScott** [lucee/lucee-dockerfiles#77]
What is the best way we start to contribute to resolving all the CVEs in Docker Containers and Lucee as a whole? The current lucee/lucee image

144 vulnerabilities found in 40 packages
  UNSPECIFIED  2
  LOW          36
  MEDIUM       29
  HIGH         47
  CRITICAL     30

**Comment by bdw429s** [comment]
@VirtuallyScott Please see this ticket: https://luceeserver.atlassian.net/browse/LDEV-4279

Most CVE's have already been addressed in Lucee 5.4 and 6.0

**Comment by tomchiverton** [comment]
This should be closed now.
