### ISSUE TITLE
(Regression) JDK-based Images Missing

### ISSUE THREAD

**Issue by jamiejackson** [lucee/lucee-dockerfiles#78]
Old images were based on JDK (versus JRE). However, recently, what should have been a patch release (5.4.1.8) introduced breaking changes for users who relied on a JDK; e.g., users of the [luceedebug step debugger](https://github.com/softwareCobbler/luceedebug/issues/43#issuecomment-1626336949).

Until then, we're stuck on 5.4.0.80.

I know this is already on your radar, but a ticket gives me something I can get automated notifications for. Otherwise, I'll continue F5-ing https://github.com/lucee/lucee-dockerfiles/blob/master/.github/workflows/main.yml obsessively.

**Comment by justincarter** [comment]
Following that commit, the `5.4.2.17` images have now been built with JDK11 and will be supported again going forward. I'll see if there's any other versions where I can fill in the gaps.

**Comment by jamiejackson** [comment]
This works for me, thanks. Feel free to close unless you have unfinished business.
